In [3]:
import math

import numpy as np
kernal_size = 5
gaussian_kernal = np.zeros((kernal_size, kernal_size))

In [4]:
center = kernal_size / 2
left =  - math.floor(center)
right = math.ceil(center)
coordinates_list = [*range(left, right)]
coordinates_list_copy_reverse = coordinates_list.copy()
coordinates_list_copy_reverse.reverse()

sigma = 1

coordinates_list.reverse()
for i, y in enumerate(coordinates_list_copy_reverse):
    for j, x in enumerate(coordinates_list):
        sum_x2_y2 = np.square([x, y]).sum()
        exp_denominator = 2 * np.square(sigma)
        gaussian_kernal[i, j] = np.exp(-(sum_x2_y2 / (exp_denominator))) / (exp_denominator * np.pi)

gaussian_kernal
        

array([[0.00291502, 0.01306423, 0.02153928, 0.01306423, 0.00291502],
       [0.01306423, 0.05854983, 0.09653235, 0.05854983, 0.01306423],
       [0.02153928, 0.09653235, 0.15915494, 0.09653235, 0.02153928],
       [0.01306423, 0.05854983, 0.09653235, 0.05854983, 0.01306423],
       [0.00291502, 0.01306423, 0.02153928, 0.01306423, 0.00291502]])

In [5]:
from convolve import convolve2D_single_Kernal
from convolve import  processImage

import cv2

img = processImage('../Bikesgray.jpg')

image_qaussian_smoothed = convolve2D_single_Kernal(img, gaussian_kernal)

cv2.imwrite('quassian_bikesgray.jpg', image_qaussian_smoothed)

True

In [6]:
laplacian_kernal = np.array([[0, -1, 0], [-1, 4, -1], [0, -1, 0]])

laplacian_of_gaussian_kernal = convolve2D_single_Kernal(gaussian_kernal, laplacian_kernal)
laplacian_of_gaussian_kernal


array([[0.01500615, 0.08833553, 0.01500615],
       [0.08833553, 0.25049036, 0.08833553],
       [0.01500615, 0.08833553, 0.01500615]])

In [12]:
img = processImage('../Bikesgray.jpg')

In [13]:
image_laplacian_of_guassian = convolve2D_single_Kernal(img, laplacian_of_gaussian_kernal)

cv2.imwrite('laplacian_of_quassian_bikesgray.jpg', image_laplacian_of_guassian)

True

In [96]:
test1 = [*range(-1, 2)] 
test = test1.copy()
test.reverse()
test1

[-1, 0, 1]

In [15]:
np.square([1, 2]).sum()

5

In [10]:
np.exp(4)

54.598150033144236

In [49]:
np.exp(-(4 / (2 * np.square(1)))) / (2 * 3.14 * np.square(1)) * 273

5.883205784011985

In [56]:
test = np.array([1,2,3,4,5,6 ,7, 8, 9])
test.reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
w = math.ceil(float(3)*float(1.5))

# If the dimension is an even number, make it uneven
if(w%2 == 0):
    # print ("even number detected, incrementing")
    w = w + 1

# Now make the mask
l_o_g_mask = []

w_range = int(math.floor(w/2))
# print "Going from " + str(-w_range) + " to " + str(w_range)
for i in range(-w_range, w_range):
    for j in range(-w_range, w_range):
        l_o_g_mask.append(l_o_g(i,j,sigma))
l_o_g_mask = np.array(l_o_g_mask)
l_o_g_mask = l_o_g_mask.reshape(w,w)

In [61]:
w = math.ceil(float(3)*float(1.5))
w_range = int(math.floor(w/2))
w_range


2

In [70]:
for i in range(-1, 1):
    print(i)

-1
0


In [69]:
for i in range(1, -1, -1):
    print(i)

1
0


In [71]:
math.ceil(2.5)

3

In [72]:
math.floor(2.5)

2